version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-90-10.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: d6bn8adgutldvs
            ssl: true
            user: cmsssntvzrvmot
            password: 9727d8c64ad1365477e004e8d197984ca6f637a8c9125f3908fdd9c51883cc70
            migrations: true
